
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-11T15:52:30-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b3adf2d29e7d1963fa8bf7e08ea3d58ef9117422",
 "version": "Beta Testing"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
